### PR TITLE
don't override sp on arm and mips64

### LINKED ISSUE #458: 1.7 regression: Ltest-init-local-signal hangs on 32bit ARM and 64bit MIPS
Ltest-init-local-signal hangs (busyloops) in 1.7.0-rc2 on 32bit ARM and 64bit MIPS (it passes on these architectures in 1.6.2):
https://buildd.debian.org/status/fetch.php?pkg=libunwind&arch=armel&ver=1.7.0~rc2-1&stamp=1676295681&raw=0
https://buildd.debian.org/status/fetch.php?pkg=libunwind&arch=armhf&ver=1.7.0~rc2-1&stamp=1676304810&raw=0
https://buildd.debian.org/status/fetch.php?pkg=libunwind&arch=mips64el&ver=1.7.0~rc2-1&stamp=1676307149&raw=0

Attaching gdb on ARM shows it is somewhere below `arm_dwarf_callback`, e.g.

```
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:47
#1  0xf7d54d7e in __GI___libc_open (file=0x10154 "/lib/ld-linux-armhf.so.3", oflag=0)
    at ../sysdeps/unix/sysv/linux/open.c:43
#2  0xf7e2679c in elf_map_image (path=<optimized out>, ei=0xffb54838) at ./elfxx.h:77
#3  dwarf_find_eh_frame_section (info=info@entry=0xffb55920)
    at dwarf/Gfind_proc_info-lsb.c:539
#4  0xf7e27392 in _Uarm_dwarf_callback (info=0xffb55920, size=<optimized out>, 
    ptr=0xffb55988) at dwarf/Gfind_proc_info-lsb.c:642
#5  0xf7d967ce in __GI___dl_iterate_phdr (
    callback=0xf7e2715d <_Uarm_dwarf_callback>, data=data@entry=0xffb55988)
    at dl-iteratephdr.c:74
#6  0xf7e276a8 in _Uarm_dwarf_find_proc_info (as=0xf7e2e220 <local_addr_space>, 
    ip=4159127624, pi=0xffb566cc, need_unwind_info=1, arg=arg@entry=0xffb5a338)
    at dwarf/Gfind_proc_info-lsb.c:807
#7  0xf7e22374 in _Uarm_find_proc_info2 (as=0xf7e2e220 <local_addr_space>, 
    ip=4159127624, pi=0xffb566cc, need_unwind_info=1, arg=arg@entry=0xffb5a338, 
    methods=methods@entry=255) at arm/Gex_tables.c:521
#8  0xf7e223fc in _Uarm_find_proc_info (as=<optimized out>, ip=<optimized out>, 
    pi=<optimized out>, need_unwind_info=<optimized out>, arg=0xffb5a338)
    at arm/Gex_tables.c:551
#9  0xf7e246e2 in fetch_proc_info (c=c@entry=0xffb562a8, ip=<optimized out>)
    at dwarf/Gparser.c:473
#10 0xf7e25e22 in find_reg_state (sr=0xffb55c48, c=0xffb562a8)
    at dwarf/Gparser.c:1021
#11 _Uarm_dwarf_step (c=c@entry=0xffb562a8) at dwarf/Gparser.c:1066
#12 0xf7e21b16 in _Uarm_step (cursor=cursor@entry=0xffb562a8) at arm/Gstep.c:124
#13 0x000106aa in stepper (c=<optimized out>) at Ltest-init-local-signal.c:17
#14 handler (num=<optimized out>, info=<optimized out>, ucontext=<optimized out>)
    at Ltest-init-local-signal.c:35
#15 <signal handler called>
#16 foo (f=f@entry=0x0) at Ltest-init-local-signal-lib.c:5
#17 0x00010598 in main () at Ltest-init-local-signal.c:58
```

@Keno I've bisected this to commit 400b3f81.

Commenting out the following line fixes the test on 32bit ARM and 64bit MIPS: [DWARF_WHERE_CFA](https://github.com/libunwind/libunwind/pull/296/files#diff-0f5a23feddc05d252aefc4228075abe0a04394565973ab8a7e6a6dd56a31fbdcR512)

### PR DESCRIPTION
**Pull request by kasperk81**
fix #458

@Keno @AdrianBunk

### CODE REVIEW

File: src/dwarf/Gparser.c [hunk 1]
```diff
@@ -520,8 +520,10 @@ setup_fde (struct dwarf_cursor *c, dwarf_state_record_t *sr)
   for (i = 0; i < DWARF_NUM_PRESERVED_REGS + 2; ++i)
     set_reg (sr, i, DWARF_WHERE_SAME, 0);
 
+#if !defined(__arm__) && _MIPS_SIM != _ABI64
```
Comment (kasperk81) [inline src/dwarf/Gparser.c:523]:
```suggestion
#if !defined(__arm__) && !(defined(UNW_TARGET_MIPS) && _MIPS_SIM == _ABI64)
```

File: src/dwarf/Gparser.c [hunk 2]
```diff
@@ -520,8 +520,10 @@ setup_fde (struct dwarf_cursor *c, dwarf_state_record_t *sr)
   for (i = 0; i < DWARF_NUM_PRESERVED_REGS + 2; ++i)
     set_reg (sr, i, DWARF_WHERE_SAME, 0);
 
+#if !defined(__arm__) && !(defined(UNW_TARGET_MIPS) && _MIPS_SIM == _ABI64)
```
Comment (kasperk81) [inline src/dwarf/Gparser.c:523]:
```suggestion
#if !defined(UNW_TARGET_ARM) && !(defined(UNW_TARGET_MIPS) && _MIPS_SIM == _ABI64)
```

**Comment by bregma** [comment]
Not entirely sure this is right, but it's not definitely wrong and it makes arm tests pass when they weren't passing before.
